"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Database, Loader2, RefreshCw, Search, Trash2, Save, Edit2, Check, X } from "lucide-react";

export interface DataDictionaryKnowledgeEntry {
  id: string;
  source_label?: string;
  table?: string;
  field?: string;
  // v1.1.17: Two-layer structure for AI understanding
  code_explanation?: string; // Inferred from schema/column comments during data exploration
  ai_understanding?: string; // Generated by AI during analysis, user-editable ground truth
  // Legacy fields kept for backwards compatibility
  meaning?: string;
  question?: string;
  confidence?: string;
  analysis_usage?: string;
  updated_at?: string;
  confirmed_at?: string;
  session_id?: string;
}

interface DataDictionarySettingsPanelProps {
  entries: DataDictionaryKnowledgeEntry[];
  total: number;
  isLoading: boolean;
  isDeleting: boolean;
  onRefresh: () => void;
  onDelete: (ids: string[]) => Promise<void>;
  onSaveUnderstanding?: (id: string, ai_understanding: string) => Promise<void>; // New callback for saving AI understanding
}

function formatDateTime(value?: string) {
  if (!value) return "-";
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return value;
  return parsed.toLocaleString("zh-CN", { hour12: false });
}

export function DataDictionarySettingsPanel({
  entries,
  total,
  isLoading,
  isDeleting,
  onRefresh,
  onDelete,
  onSaveUnderstanding,
}: DataDictionarySettingsPanelProps) {
  const [keyword, setKeyword] = useState("");
  const [sourceFilter, setSourceFilter] = useState("all");
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingText, setEditingText] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  const sourceOptions = useMemo(() => {
    const values = Array.from(
      new Set(
        entries
          .map((item) => String(item.source_label || "").trim())
          .filter(Boolean)
      )
    );
    return values.sort((left, right) => left.localeCompare(right, "zh-CN"));
  }, [entries]);

  const filteredEntries = useMemo(() => {
    const normalizedKeyword = keyword.trim().toLowerCase();

    return entries.filter((item) => {
      const sourceLabel = String(item.source_label || "").trim();
      if (sourceFilter !== "all" && sourceLabel !== sourceFilter) {
        return false;
      }

      if (!normalizedKeyword) {
        return true;
      }

      const blob = [
        item.id,
        sourceLabel,
        item.table,
        item.field,
        item.meaning,
        item.question,
        item.analysis_usage,
        item.confidence,
      ]
        .map((value) => String(value || "").toLowerCase())
        .join(" ");

      return blob.includes(normalizedKeyword);
    });
  }, [entries, keyword, sourceFilter]);

  useEffect(() => {
    setSelectedIds((prev) => {
      if (prev.size === 0) return prev;
      const validIdSet = new Set(entries.map((item) => item.id));
      const next = new Set(Array.from(prev).filter((id) => validIdSet.has(id)));
      return next;
    });
  }, [entries]);

  const toggleSelected = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const selectAllVisible = () => {
    setSelectedIds(new Set(filteredEntries.map((item) => item.id)));
  };

  const clearSelection = () => {
    setSelectedIds(new Set());
  };

  const handleDelete = async (ids: string[]) => {
    if (!ids.length) return;

    const confirmed = window.confirm(
      ids.length === 1
        ? "确认删除这条数据字典记录吗？"
        : `确认删除选中的 ${ids.length} 条数据字典记录吗？`
    );
    if (!confirmed) {
      return;
    }

    await onDelete(ids);
    setSelectedIds((prev) => {
      const next = new Set(prev);
      ids.forEach((id) => next.delete(id));
      return next;
    });
  };

  const handleEditStart = (entry: DataDictionaryKnowledgeEntry) => {
    setEditingId(entry.id);
    setEditingText(entry.ai_understanding || entry.meaning || "");
  };

  const handleEditCancel = () => {
    setEditingId(null);
    setEditingText("");
  };

  const handleEditSave = async (id: string) => {
    if (!onSaveUnderstanding) {
      console.warn("onSaveUnderstanding callback not provided");
      return;
    }
    setIsSaving(true);
    try {
      await onSaveUnderstanding(id, editingText);
      setEditingId(null);
      setEditingText("");
    } catch (error) {
      console.error("Failed to save understanding:", error);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="mt-4 flex h-full min-h-0 flex-col gap-4 overflow-hidden">
      <section className="rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-gray-950">
        <div className="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-800">
          <div className="min-w-0">
            <div className="flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-slate-100">
              <Database className="h-4 w-4 text-cyan-600" />
              AI理解的数据字典
            </div>
            <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">
              查看和编辑AI在分析过程中生成的字段理解。点击字段编辑AI的理解，保存后作为后续分析的参考。
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="rounded-full border border-slate-200 px-2.5 py-1 text-xs text-slate-600 dark:border-slate-700 dark:text-slate-300">
              总计 {total} 条
            </span>
            <Button variant="outline" size="sm" onClick={onRefresh} disabled={isLoading || isDeleting}>
              {isLoading ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="mr-2 h-3.5 w-3.5" />}
              刷新
            </Button>
          </div>
        </div>

        <div className="grid gap-3 px-4 py-4 md:grid-cols-[1fr_220px_auto_auto_auto]">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" />
            <Input
              value={keyword}
              onChange={(event) => setKeyword(event.target.value)}
              placeholder="搜索表名、字段、含义、问题或用途"
              className="pl-9"
            />
          </div>

          <Select value={sourceFilter} onValueChange={setSourceFilter}>
            <SelectTrigger>
              <SelectValue placeholder="按数据源筛选" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">全部数据源</SelectItem>
              {sourceOptions.map((source) => (
                <SelectItem key={source} value={source}>
                  {source}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Button variant="outline" size="sm" onClick={selectAllVisible} disabled={!filteredEntries.length || isDeleting}>
            全选当前
          </Button>
          <Button variant="outline" size="sm" onClick={clearSelection} disabled={selectedIds.size === 0 || isDeleting}>
            清空选择
          </Button>
          <Button
            variant="destructive"
            size="sm"
            disabled={selectedIds.size === 0 || isDeleting}
            onClick={() => {
              void handleDelete(Array.from(selectedIds));
            }}
          >
            {isDeleting ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" /> : <Trash2 className="mr-2 h-3.5 w-3.5" />}
            撤销选中
          </Button>
        </div>
      </section>

      <section className="min-h-0 flex-1 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-gray-950">
        <div className="flex items-center justify-between border-b border-slate-200 px-4 py-3 text-xs text-slate-500 dark:border-slate-800 dark:text-slate-400">
          <span>筛选结果 {filteredEntries.length} 条</span>
          <span>已选择 {selectedIds.size} 条</span>
        </div>

        <div className="h-full overflow-auto p-3">
          {isLoading ? (
            <div className="flex h-full items-center justify-center text-sm text-slate-500">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              正在加载数据字典...
            </div>
          ) : filteredEntries.length === 0 ? (
            <div className="flex h-full items-center justify-center text-sm text-slate-500">
              当前没有匹配的数据字典记录。
            </div>
          ) : (
            <div className="space-y-2">
              {filteredEntries.map((entry) => {
                const checked = selectedIds.has(entry.id);
                const subject = [entry.table, entry.field].filter(Boolean).join(".") || "(未命名字段)";
                const isEditing = editingId === entry.id;
                const aiUnderstanding = entry.ai_understanding || entry.meaning || "";

                return (
                  <div
                    key={entry.id}
                    className="rounded-lg border border-slate-200 p-3 dark:border-slate-800"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex min-w-0 flex-1 items-start gap-2">
                        <Checkbox checked={checked} onCheckedChange={() => toggleSelected(entry.id)} className="mt-0.5" />
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <span className="rounded-full border border-slate-200 px-2 py-0.5 text-[10px] text-slate-600 dark:border-slate-700 dark:text-slate-300">[{entry.id}]</span>
                            <span className="text-sm font-medium text-slate-900 dark:text-slate-100">{subject}</span>
                            {entry.source_label ? (
                              <span className="rounded-full border border-cyan-200 bg-cyan-50 px-2 py-0.5 text-[10px] text-cyan-700 dark:border-cyan-900 dark:bg-cyan-950/30 dark:text-cyan-300">
                                {entry.source_label}
                              </span>
                            ) : null}
                          </div>

                          {/* Code explanation from schema */}
                          {entry.code_explanation ? (
                            <div className="mt-2 text-sm leading-6 text-slate-700 dark:text-slate-300">
                              <span className="font-medium text-slate-600 dark:text-slate-400">架构定义:</span> {entry.code_explanation}
                            </div>
                          ) : null}

                          {/* AI understanding - editable */}
                          <div className="mt-2">
                            {isEditing ? (
                              <div className="space-y-2">
                                <label className="text-xs font-medium text-slate-600 dark:text-slate-400">编辑 AI 理解的字段定义</label>
                                <Textarea
                                  value={editingText}
                                  onChange={(e) => setEditingText(e.target.value)}
                                  placeholder="输入此字段的语义含义、用途、范围等信息..."
                                  className="min-h-[80px] resize-none"
                                />
                                <div className="flex gap-2">
                                  <Button
                                    size="sm"
                                    variant="default"
                                    onClick={() => handleEditSave(entry.id)}
                                    disabled={isSaving}
                                    className="gap-2"
                                  >
                                    {isSaving ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}
                                    保存
                                  </Button>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={handleEditCancel}
                                    disabled={isSaving}
                                    className="gap-2"
                                  >
                                    <X className="h-3.5 w-3.5" />
                                    取消
                                  </Button>
                                </div>
                              </div>
                            ) : (
                              <div>
                                <div className="flex items-start justify-between gap-2">
                                  <span className="text-xs font-medium text-slate-600 dark:text-slate-400">AI 理解:</span>
                                  <Button
                                    size="sm"
                                    variant="ghost"
                                    onClick={() => handleEditStart(entry)}
                                    disabled={isDeleting || isSaving}
                                    className="h-5 px-2 text-xs text-cyan-600 hover:text-cyan-700 dark:text-cyan-400"
                                  >
                                    <Edit2 className="h-3 w-3" />
                                  </Button>
                                </div>
                                <div className="mt-1 text-sm leading-6 text-slate-800 dark:text-slate-200">
                                  {aiUnderstanding || <span className="italic text-slate-400">（暂无定义）</span>}
                                </div>
                              </div>
                            )}
                          </div>

                          <div className="mt-2 text-[11px] text-slate-500 dark:text-slate-400">
                            最近更新: {formatDateTime(entry.updated_at || entry.confirmed_at)}
                          </div>
                        </div>
                      </div>

                      <Button
                        variant="outline"
                        size="sm"
                        className="shrink-0 text-rose-600 hover:text-rose-700"
                        disabled={isDeleting || isSaving}
                        onClick={() => {
                          void handleDelete([entry.id]);
                        }}
                      >
                        <Trash2 className="mr-2 h-3.5 w-3.5" />
                        删除
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
